#ifndef CODES_ERREURS_H
#define CODES_ERREURS_H

#define ERREUR 0
#define ERREUR_PAS_CONNECTEE -10
#define ERREUR_MAUVAIS_MOT_DE_PASSE -11
#define ERREUR_COMPTE_INEXISTANTE -12
#define ERREUR_COMPTE_CONNECTEE -13
#define ERREUR_COMPTE_PROPRE -14
#define ERREUR_SAISIE -20
#define ERREUR_PSEUDO_EXISTANT -21
#define ERREUR_MOT_DE_PASSE_COURT -22
#define ERREUR_GROUPE_EXISTE_DEJA -30
#define ERREUR_GROUPE_INNEXISTANT -31
#define OK 1

#endif